export const SKILLS = [
  {
    name: "App / Cloud Engineering",
    data: [
      "Python / JavaScript / Go",
      "REST & GraphQL APIs",
      "Microservices architecture",
      "SQL & NoSQL databases",
      "Docker & containerization",
      "Kubernetes orchestration",
      "CI/CD pipelines",
      "Cloud platforms (AWS, Azure, GCP)",
      "Serverless (Lambda, Firebase)",
      "Authentication (OAuth, JWT)",
      "System design",
      "Caching (Redis)",
      "Networking fundamentals",
      "Load balancing",
      "Logging & monitoring",
      "Security best practices",
      "Infrastructure as Code (Terraform)",
      "Version control (Git)",
      "API rate limiting & throttling",
      "Event-driven architecture",
      "gRPC implementation",
      "Service mesh (Istio/Linkerd)",
      "Secrets management (Vault)",
      "Feature flagging systems",
      "Blue-green deployments",
      "Canary releases",
      "API gateway configuration",
      "Edge caching (CDN strategies)",
      "WebSockets & real-time systems",
      "Distributed tracing",
      "API versioning strategies",
      "Multi-cloud architecture",
      "Cold start optimization (serverless)",
      "Reverse proxy configuration",
      "High availability design",
      "Fault tolerance engineering",
      "API documentation (Swagger/OpenAPI advanced)",
      "Backend performance profiling",
    ],
  },
  {
    name: "Business Analysis",
    data: [
      "Requirements gathering",
      "Stakeholder interviews",
      "Process mapping",
      "User stories & acceptance criteria",
      "Documentation (BRD, FRD)",
      "Data analysis basics",
      "Gap analysis",
      "Wireframing basics",
      "Communication & facilitation",
      "Agile/Scrum",
      "Jira/Confluence",
      "Problem-solving",
      "Business process reengineering",
      "Use case modeling",
      "SWOT analysis",
      "Journey mapping",
      "KPI definition frameworks",
      "Workshop facilitation",
      "Decision modeling (DMN)",
      "Business capability mapping",
      "Data requirement specification",
      "Hypothesis testing",
      "Stakeholder alignment strategy",
      "Change impact analysis",
      "Service blueprinting",
      "Customer segmentation",
      "Root cause analysis (5 Whys)",
      "Value stream mapping",
      "Business case development",
      "Cost-benefit analysis",
      "Process automation analysis",
      "Scenario planning",
      "Metrics dashboard planning",
      "Experimentation planning",
      "Insight generation",
    ],
  },
  {
    name: "Data Analysis",
    data: [
      "Excel (advanced)",
      "SQL",
      "Power BI / Tableau",
      "Data cleaning",
      "Data visualization",
      "Descriptive statistics",
      "Inferential statistics",
      "Predictive modeling basics",
      "Dashboard design",
      "Data storytelling",
      "Python (Pandas)",
      "Google Sheets automation",
      "A/B testing basics",
      "Reporting",
      "Data validation",
      "Business metrics understanding",
      "Cohort analysis",
      "Funnel analysis",
      "Data blending",
      "KPI tracking frameworks",
      "SQL query optimization",
      "Data annotation",
      "Heatmap analysis",
      "Clickstream analysis",
      "Forecasting basics",
      "Data pipeline validation",
      "Regression analysis",
      "Outlier detection",
      "Data ethics & governance basics",
      "Data catalog usage",
      "Spreadsheet modeling",
      "Dashboard performance tuning",
      "Data reconciliation",
      "Metric standardization",
      "Data sampling",
      "Survey analysis",
    ],
  },
  {
    name: "Data Engineering",
    data: [
      "Python / Scala",
      "SQL (advanced)",
      "ETL/ELT pipelines",
      "Apache Spark",
      "Hadoop ecosystem",
      "Data warehousing",
      "Data lakes",
      "Airflow orchestration",
      "Kafka (streaming)",
      "Data modeling",
      "Cloud data tools",
      "APIs integration",
      "Batch processing",
      "Real-time processing",
      "Data quality management",
      "Version control",
      "Performance optimization",
      "Schema evolution",
      "Data partitioning strategies",
      "Columnar storage (Parquet/ORC)",
      "Query engine optimization",
      "Data lineage tracking",
      "CDC (Change Data Capture)",
      "Data mesh architecture",
      "Data contracts",
      "Pipeline orchestration design",
      "Storage optimization",
      "Compression techniques",
      "Distributed query systems",
      "Data sandboxing",
      "Data observability",
      "Backup & recovery strategies",
      "Data replication",
      "Metadata management systems",
      "Lakehouse architecture",
      "Data versioning",
      "Cost-efficient data storage",
    ],
  },
  {
    name: "Data Science",
    data: [
      "Python / R",
      "Statistics & probability",
      "Machine learning algorithms",
      "Data cleaning",
      "Feature engineering",
      "Model evaluation",
      "Data visualization",
      "Pandas / NumPy",
      "Scikit-learn",
      "Deep learning basics",
      "NLP basics",
      "Experiment design",
      "SQL",
      "Big data tools",
      "Storytelling",
      "Model deployment strategies",
      "Model monitoring",
      "Drift detection",
      "Hyperparameter tuning",
      "Bayesian modeling",
      "Graph analytics",
      "Simulation modeling",
      "Synthetic data generation",
      "Ensemble methods",
      "Feature importance analysis",
      "Dimensionality reduction",
      "Model interpretability",
      "Reinforcement learning basics (practical)",
      "Statistical inference",
      "Decision modeling",
      "Optimization techniques",
      "Time-series forecasting (advanced)",
      "Experiment tracking (MLflow)",
      "AI ethics",
      "Data augmentation",
    ],
  },
  {
    name: "DevOps Engineering",
    data: [
      "CI/CD pipelines",
      "Docker",
      "Kubernetes",
      "Terraform",
      "AWS/GCP/Azure",
      "Bash scripting",
      "Monitoring (Prometheus, Grafana)",
      "Logging systems",
      "Git workflows",
      "Infrastructure automation",
      "Networking",
      "Security integration",
      "System reliability",
      "Release management",
      "Configuration management",
      "GitOps workflows",
      "Infrastructure drift detection",
      "Secrets rotation",
      "Deployment rollbacks",
      "Incident management systems",
      "Chaos engineering practices",
      "Load testing",
      "Capacity planning",
      "Backup automation",
      "Infrastructure cost monitoring",
      "Blue/green infra management",
      "Self-healing systems",
      "Runtime security",
      "Immutable infrastructure",
      "Pipeline security",
      "Container security scanning",
      "Environment parity management",
      "SLA/SLO definition",
      "Release orchestration",
      "Dev environment automation"
    ],
  },

  {
    name: "Ethical Hacking",
    data: [
      "Networking fundamentals",
      "Linux systems",
      "Penetration testing",
      "Web security (OWASP Top 10)",
      "Burp Suite",
      "Metasploit",
      "Nmap",
      "Wireshark",
      "Scripting (Python, Bash)",
      "Vulnerability scanning",
      "Social engineering",
      "Cryptography basics",
      "Exploit development",
      "OSINT",
      "Threat modeling",
      "API penetration testing",
      "Binary exploitation",
      "Secure code review",
      "Attack surface mapping",
      "Privilege escalation techniques",
      "Cloud misconfiguration testing",
      "Red team simulations",
      "Password cracking techniques",
      "Post-exploitation techniques",
      "Security tool automation",
      "Adversary emulation",
      "Network pivoting",
      "Bug bounty reporting",
      "Threat scenario design",
      "Container security testing",
      "Identity attack techniques",
      "Lateral movement strategies",
      "Zero-day research basics",
      "Security misconfiguration audits",
    ],
  },
  {
    name: "Governance, Risk & Compliance",
    data: [
      "Risk assessment",
      "Compliance frameworks (ISO 27001, NIST)",
      "Policy writing",
      "Audit processes",
      "Risk mitigation",
      "Documentation",
      "Vendor risk management",
      "Legal/regulatory knowledge",
      "Security awareness training",
      "Business continuity planning",
      "Incident response planning",
      "Data privacy laws",
      "Reporting",
      "Internal controls",
      "Control framework mapping",
      "Risk scoring models",
      "Regulatory gap analysis",
      "Compliance automation",
      "Policy lifecycle management",
      "Third-party audits",
      "Risk dashboards",
      "Audit evidence collection",
      "Control testing methodologies",
      "Risk heatmaps",
      "Governance frameworks design",
      "Data classification policies",
      "Privacy impact assessments",
      "Compliance reporting automation",
      "Vendor due diligence",
      "Risk register management",
      "Legal risk interpretation",
      "Internal audit coordination",
      "Regulatory monitoring",
      "Ethics & compliance programs",
    ],
  },
  {
    name: "Product Design",
    data: [
      "UI design (Figma)",
      "UX research",
      "Wireframing",
      "Prototyping",
      "Interaction design",
      "Design systems",
      "Usability testing",
      "Visual hierarchy",
      "Typography & color theory",
      "Accessibility (WCAG)",
      "User flows",
      "Micro-interactions",
      "Design thinking",
      "Product thinking",
      "Collaboration with devs",
      "Analytics interpretation",
      "UX metrics tracking",
      "Design QA processes",
      "Accessibility auditing",
      "UX copy strategy",
      "Design critique facilitation",
      "Product discovery workshops",
      "Design sprint facilitation",
      "Information architecture",
      "Heuristic evaluation",
      "UX benchmarking",
      "Interaction prototyping (advanced)",
      "Design token systems",
      "Cross-platform design adaptation",
      "User onboarding design",
      "Behavioral design principles",
      "Dark mode design systems",
      "Personalization design",
      "UX analytics tools",
      "Motion storytelling",
      "AI-assisted design workflows",
    ],
  },
  {
    name: "Project Management",
    data: [
      "Project planning",
      "Scheduling (Gantt charts)",
      "Agile/Scrum/Kanban",
      "Risk management",
      "Budgeting",
      "Stakeholder management",
      "Communication",
      "Jira/Asana/Trello",
      "Resource allocation",
      "Conflict resolution",
      "Reporting",
      "Documentation",
      "KPI tracking",
      "Change management",
      "Time management",
      "Roadmapping",
      "Dependency management",
      "Sprint retrospectives facilitation",
      "Stakeholder reporting frameworks",
      "Program tracking dashboards",
      "Cross-functional alignment",
      "Decision-making frameworks", 
      "Escalation management",
      "Delivery forecasting",
      "Capacity forecasting",
      "OKR planning",
      "Risk escalation strategy",
      "Governance structures",
      "Agile coaching",
      "Delivery optimization",
      "Vendor coordination",
      "Portfolio tracking",
      "Workflow optimization",
      "Strategic planning",
      "Change readiness assessment",
    ],
  },
  {
    name: "SOC Analyst",
    data: [
      "SIEM tools (Splunk, QRadar)",
      "Log analysis",
      "Threat detection",
      "Incident response",
      "Network security",
      "Malware analysis basics",
      "Threat intelligence",
      "Security alerts triage",
      "Vulnerability management",
      "Endpoint security",
      "Firewall & IDS/IPS",
      "Forensics basics",
      "Reporting",
      "Scripting basics",
      "Risk assessment",
      "Threat hunting methodologies",
      "Security automation scripting",
      "Detection rule creation",
      "Incident playbook development",
      "Log correlation techniques",
      "Behavioral analytics",
      "Alert tuning",
      "Cloud threat monitoring",
      "Endpoint detection tuning",
      "Threat intelligence integration",
      "Security orchestration (SOAR)",
      "Incident timeline reconstruction",
      "Threat pattern recognition",
      "Detection engineering basics",
      "Forensic artifact analysis",
      "Security data enrichment",
      "Anomaly detection",
      "Attack chain mapping",
      "Alert prioritization frameworks",
      "SOC workflow optimization",
    ],
  },
];
