export const SKILLS = [
  {
    name: "App / Cloud Engineering",
    data: [
      "Python / JavaScript / Go",
      "REST & GraphQL APIs",
      "Microservices architecture",
      "SQL & NoSQL databases",
      "Docker & containerization",
      "Kubernetes orchestration",
      "CI/CD pipelines",
      "Cloud platforms (AWS, Azure, GCP)",
      "Serverless (Lambda, Firebase)",
      "Authentication (OAuth, JWT)",
      "System design",
      "Caching (Redis)",
      "Networking fundamentals",
      "Load balancing",
      "Logging & monitoring",
      "Security best practices",
      "Infrastructure as Code (Terraform)",
      "Version control (Git)",
    ],
  },
  {
    name: "Business Analysis",
    data: [
      "Requirements gathering",
      "Stakeholder interviews",
      "Process mapping",
      "User stories & acceptance criteria",
      "Documentation (BRD, FRD)",
      "Data analysis basics",
      "Gap analysis",
      "Wireframing basics",
      "Communication & facilitation",
      "Agile/Scrum",
      "Jira/Confluence",
      "Problem-solving",
      "Business process reengineering",
      "Use case modeling",
      "SWOT analysis",
    ],
  },
  {
    name: "Data Analysis",
    data: [
      "Excel (advanced)",
      "SQL",
      "Power BI / Tableau",
      "Data cleaning",
      "Data visualization",
      "Descriptive statistics",
      "Inferential statistics",
      "Predictive modeling basics",
      "Dashboard design",
      "Data storytelling",
      "Python (Pandas)",
      "Google Sheets automation",
      "A/B testing basics",
      "Reporting",
      "Data validation",
      "Business metrics understanding",
    ],
  },
  {
    name: "Data Engineering",
    data: [
      "Python / Scala",
      "SQL (advanced)",
      "ETL/ELT pipelines",
      "Apache Spark",
      "Hadoop ecosystem",
      "Data warehousing",
      "Data lakes",
      "Airflow orchestration",
      "Kafka (streaming)",
      "Data modeling",
      "Cloud data tools",
      "APIs integration",
      "Batch processing",
      "Real-time processing",
      "Data quality management",
      "Version control",
      "Performance optimization",
    ],
  },
  {
    name: "Data Science",
    data: [
      "Python / R",
      "Statistics & probability",
      "Machine learning algorithms",
      "Data cleaning",
      "Feature engineering",
      "Model evaluation",
      "Data visualization",
      "Pandas / NumPy",
      "Scikit-learn",
      "Deep learning basics",
      "NLP basics",
      "Experiment design",
      "SQL",
      "Big data tools",
      "Storytelling",
    ],
  },
  {
    name: "DevOps Engineering",
    data: [
      "CI/CD pipelines",
      "Docker",
      "Kubernetes",
      "Terraform",
      "AWS/GCP/Azure",
      "Bash scripting",
      "Monitoring (Prometheus, Grafana)",
      "Logging systems",
      "Git workflows",
      "Infrastructure automation",
      "Networking",
      "Security integration",
      "System reliability",
      "Release management",
      "Configuration management",
    ],
  },

  {
    name: "Ethical Hacking",
    data: [
      "Networking fundamentals",
      "Linux systems",
      "Penetration testing",
      "Web security (OWASP Top 10)",
      "Burp Suite",
      "Metasploit",
      "Nmap",
      "Wireshark",
      "Scripting (Python, Bash)",
      "Vulnerability scanning",
      "Social engineering",
      "Cryptography basics",
      "Exploit development",
      "OSINT",
    ],
  },
  {
    name: "Governance, Risk & Compliance",
    data: [
      "Risk assessment",
      "Compliance frameworks (ISO 27001, NIST)",
      "Policy writing",
      "Audit processes",
      "Risk mitigation",
      "Documentation",
      "Vendor risk management",
      "Legal/regulatory knowledge",
      "Security awareness training",
      "Business continuity planning",
      "Incident response planning",
      "Data privacy laws",
      "Reporting",
      "Internal controls",
    ],
  },
  {
    name: "Product Design",
    data: [
      "UI design (Figma)",
      "UX research",
      "Wireframing",
      "Prototyping",
      "Interaction design",
      "Design systems",
      "Usability testing",
      "Visual hierarchy",
      "Typography & color theory",
      "Accessibility (WCAG)",
      "User flows",
      "Micro-interactions",
      "Design thinking",
      "Product thinking",
      "Collaboration with devs",
      "Analytics interpretation",
    ],
  },
  {
    name: "Project Management",
    data: [
      "Project planning",
      "Scheduling (Gantt charts)",
      "Agile/Scrum/Kanban",
      "Risk management",
      "Budgeting",
      "Stakeholder management",
      "Communication",
      "Jira/Asana/Trello",
      "Resource allocation",
      "Conflict resolution",
      "Reporting",
      "Documentation",
      "KPI tracking",
      "Change management",
      "Time management",
    ],
  },
  {
    name: "SOC Analyst",
    data: [
      "SIEM tools (Splunk, QRadar)",
      "Log analysis",
      "Threat detection",
      "Incident response",
      "Network security",
      "Malware analysis basics",
      "Threat intelligence",
      "Security alerts triage",
      "Vulnerability management",
      "Endpoint security",
      "Firewall & IDS/IPS",
      "Forensics basics",
      "Reporting",
      "Scripting basics",
      "Risk assessment",
    ],
  },
];
