export const SPECIALIZATION = [
  {
    category: "App / Cloud Engineering",
    data: [
      "Cloud Architecture",
      "Backend Engineering",
      "Frontend Engineering",
      "Fullstack Engineering",
      "Mobile App Development (iOS)",
      "Mobile App Development (Android)",
      "Cross-platform Development (Flutter/React Native)",
      "Serverless Engineering",
      "API Engineering",
      "Microservices Engineering",
      "Cloud Security Engineering",
      "Site Reliability Engineering (SRE)",
      "Platform Engineering",
      "Infrastructure Engineering",
      "Edge Computing Engineering",
      "IoT Cloud Engineering",
      "Distributed Systems Engineering",
      "DevSecOps Engineering",
      "Cloud Networking Engineering",
      "Database Engineering",
      "AI Infrastructure Engineering",
    ],
  },
  {
    name: "Business Analysis",
    data: [
      "Product Analysis",
      "Business Intelligence Analysis",
      "Process Analysis",
      "Operations Analysis",
      "Financial Analysis",
      "Strategy Analysis",
      "Market Research Analysis",
      "Data-driven Business Analysis",
      "UX Research Analysis",
      "Customer Experience Analysis",
      "Risk Analysis",
      "Compliance Analysis",
      "Supply Chain Analysis",
      "Agile Business Analysis",
      "Digital Transformation Analysis",
      "CRM Analysis",
      "HR/People Analytics",
      "Pricing Analysis",
      "Growth Analysis",
      "Competitive Intelligence Analysis",
    ],
  },
  {
    name: " Data Analysis",
    data: [
      "Business Intelligence (BI) Analyst",
      "Product Analyst",
      "Marketing Analyst",
      "Financial Analyst",
      "Operations Analyst",
      "Growth Analyst",
      "Customer Insights Analyst",
      "Risk Analyst",
      "Fraud Analyst",
      "Healthcare Data Analyst",
      "Supply Chain Analyst",
      "Web Analytics Specialist",
      "SEO/Data Analyst",
      "Social Media Analyst",
      "Sales Analyst",
      "Sports Analyst",
      "Geospatial Analyst",
      "Survey/Data Research Analyst",
      "A/B Testing Analyst",
      "Data Visualization Specialist",
    ],
  },
  {
    name: "Data Engineering",
    data: [
      " Big Data Engineer",
      "Streaming Data Engineer",
      "ETL Engineer",
      "Data Warehouse Engineer",
      "Data Lake Engineer",
      "Analytics Engineer",
      "Machine Learning Data Engineer",
      "Cloud Data Engineer",
      "Data Platform Engineer",
      "Pipeline Engineer",
      "Database Engineer",
      "Data Infrastructure Engineer",
      "Real-time Data Engineer",
      "Data Integration Engineer",
      "Data Quality Engineer",
      "Data Governance Engineer",
      "Metadata Engineer",
      "IoT Data Engineer",
      "Distributed Systems Data Engineer",
      "AI Data Pipeline Engineer",
    ],
  },
  {
    name: "Data Science",
    data: [
      "Machine Learning Engineer",
      "AI Engineer",
      "Deep Learning Engineer",
      "NLP Engineer",
      "Computer Vision Engineer",
      "Recommendation Systems Engineer",
      "Quantitative Analyst",
      "Research Scientist",
      "Applied Data Scientist",
      "Decision Scientist",
      "Behavioral Data Scientist",
      "Marketing Data Scientist",
      "Financial Data Scientist",
      "Healthcare Data Scientist",
      "Sports Data Scientist",
      "Geospatial Data Scientist",
      "AI Ethics Specialist",
      "Causal Inference Specialist",
      "Time Series Analyst",
      "Reinforcement Learning Engineer",
      "AI Product Scientist",
    ],
  },
  {
    name: "DevOps Engineering",
    data: [
      "Site Reliability Engineer (SRE)",
      "Cloud DevOps Engineer",
      "DevSecOps Engineer",
      "Platform Engineer",
      "Cloud DevOps Engineer",
      "DevSecOps Engineer",
      "Infrastructure Engineer",
      "CI/CD Engineer",
      "Release Engineer",
      "Automation Engineer",
      "Kubernetes Engineer",
      "Containerization Specialist",
      "Observability Engineer",
      "Monitoring Engineer",
      "Build Engineer",
      "Systems Engineer",
      "Reliability Engineer",
      "Cloud Automation Engineer",
      "GitOps Engineer",
      "Edge DevOps Engineer",
      "Performance Engineer",
      "Chaos Engineering Specialist",
    ],
  },
  {
    name: "Ethical Hacking",
    data: [
      "Web Application Pentester",
      "Network Pentester",
      "Mobile App Pentester",
      "API Security Tester",
      "Cloud Security Tester",
      "Red Team Operator",
      "Bug Bounty Hunter",
      "Social Engineering Specialist",
      "Exploit Developer",
      "Malware Analyst",
      "Reverse Engineer",
      "Wireless Network Tester",
      "IoT Security Tester",
      "Blockchain Security Auditor",
      "Threat Hunter",
      "Security Researcher",
      "OSINT Specialist",
      "Digital Forensics Expert",
      "Vulnerability Researcher",
      "Cyber Threat Intelligence Analyst",
    ],
  },
  {
    name: "Governance, Risk & Compliance",
    data: [
      "IT Compliance Specialist",
      "Risk Management Analyst",
      "Information Security Analyst",
      "Privacy Specialist (GDPR/NDPR)",
      "Internal Auditor",
      "External Auditor",
      "Third-party Risk Manager",
      "Vendor Risk Analyst",
      "Policy & Governance Specialist",
      "Business Continuity Planner",
      "Disaster Recovery Specialist",
      "Regulatory Compliance Analyst",
      "Security Awareness Manager",
      "Data Protection Officer (DPO)",
      "IT Governance Analyst",
      "Control Testing Analyst",
      "ESG (Governance) Analyst",
      "Cyber Risk Consultant",
      "Legal Tech Compliance Specialist",
      "Financial Compliance Analyst",
    ],
  },
  {
    name: "Product Design",
    data: [
      "UX Designer",
      "UI Designer",
      "Product Designer",
      "Interaction Designer",
      "Visual Designer",
      "UX Researcher",
      "Design Systems Designer",
      "UX Writer",
      "Content Designer",
      "Service Designer",
      "Experience Designer",
      "Growth Designer",
      "Conversion Rate Optimization (CRO) Designer",
      "Mobile Product Designer",
      "Web Product Designer",
      "Accessibility Designer",
      "Motion Designer (UI animation)",
      "Prototyping Specialist",
      "Design Strategist",
      "AI Product Designer",
    ],
  },
  {
    name: "Project Management",
    data: [
      "Agile Project Manager",
      "Scrum Master",
      "Program Manager",
      "Portfolio Manager",
      "Technical Project Manager",
      "IT Project Manager",
      "Construction Project Manager",
      "Product Operations Manager",
      "Transformation Manager",
      "Risk Project Manager",
      "Change Management Specialist",
      "PMO (Project Management Office) Lead",
      "Delivery Manager",
      "Operations Manager",
      "Strategy Execution Manager",
      "Digital Project Manager",
      "Event Project Manager",
      "Healthcare Project Manager",
      "Finance Project Manager",
      "Government Project Manager",
    ],
  },
  {
    name: "SOC Analyst",
    data: [
      " Tier 1 SOC Analyst",
      "Tier 2 SOC Analyst",
      "Tier 3 SOC Analyst",
      "Threat Intelligence Analyst",
      "Incident Response Analyst",
      "Digital Forensics Analyst",
      "Malware Analyst",
      "Threat Hunter",
      "Blue Team Specialist",
      "Detection Engineer",
      "SIEM Engineer",
      "Security Monitoring Engineer",
      "Endpoint Detection Specialist",
      "Network Security Analyst",
      "Vulnerability Analyst",
      "Cyber Fusion Analyst",
      "Security Automation Engineer",
      "Log Analysis Specialist",
      "Insider Threat Analyst",
      "Cloud SOC Analyst",
    ],
  },
];
